<a href="https://colab.research.google.com/github/Prdazk/collabku/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Dari list
a = np.array([1, 2, 3])
print("Array:", a)

# Array dengan nol
b = np.zeros((3, 3))
print("\nZeros:\n", b)

# Array dengan satu
c = np.ones((2, 4))
print("\nOnes:\n", c)

# Array kosong (nilainya acak dari memori)
d = np.empty((2, 2))
print("\nEmpty:\n", d)

# Range mirip range() di Python
e = np.arange(0, 10, 2)
print("\nArange:", e)

# Linspace (bagi rata rentang angka)
f = np.linspace(0, 1, 5)
print("\nLinspace:", f)


Array: [1 2 3]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Empty:
 [[3.00805015e-315 0.00000000e+000]
 [6.86135610e-310 5.76244178e-317]]

Arange: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]
